# Generated by Django 4.2.4 on 2023-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_BLR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='photo',
            field=models.ImageField(null=True, upload_to='my_ experience/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='photo',
            field=models.ImageField(null=True, upload_to='history/'),
        ),
    ]
