# Generated by Django 4.2.4 on 2023-08-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_BLR', '0002_alter_experience_photo_alter_news_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='profile_picture',
        ),
    ]
