# Generated by Django 4.2.4 on 2023-09-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_BLR', '0003_remove_experience_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='photo',
            field=models.ImageField(null=True, upload_to='blog/history/'),
        ),
    ]
