# Generated by Django 4.2.4 on 2023-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_BLR', '0004_alter_technology_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='photo',
            field=models.ImageField(null=True, upload_to='Blog/'),
        ),
    ]
