# Generated by Django 4.2.4 on 2023-09-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_BLR', '0006_alter_experience_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='insta',
            field=models.URLField(),
        ),
    ]
