# Generated by Django 4.2.5 on 2023-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_BLR', '0007_alter_about_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(null=True, upload_to='Blog/news/'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='photo',
            field=models.ImageField(null=True, upload_to='Blog/recipes/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='photo',
            field=models.ImageField(null=True, upload_to='Blog/Technologies/'),
        ),
    ]
