# Generated by Django 4.2.4 on 2023-08-24 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Talks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='talks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='Talks.talks'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
